### ISSUE TITLE
Intent Column empty after the first step

### ISSUE THREAD

**Issue by anjeri** [e-merlin/eMERLIN_CASA_pipeline#101]

**Comment by anjeri** [comment]
Hi @jmoldon 
After importing the fits file(s), the Intent Column of the sources on the Observation summary turns up empty i.e it does not specify whether the source is the target, phscal, fluxcal, bpcal or ptcal.
Thanks.

**Comment by jmoldon** [comment]
The `Intent` comes from the inputs file as specified by the user. 

In your first run you didn't include the source names, and that is why the intent was empty in the Observation summary section after the first step.

Once you have included the source names in the inputs.txt file, the weblog will be updated after the next execution. Note that you can run the pipeline without any step selected. That will update the weblog.
