### ISSUE TITLE
VLASS self-calibration

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/eMERLIN_CASA_pipeline#102]
Hey Javi, 

Just a thought. Have you implemented the VLASS self-calibration step that you showed me a while back into the pipeline. i.e. the source finding from the VLASS images and then doing multi-source self-cal / multi-component model calibration? fyi I have the MSSC CASA v0.1 finally written and am just testing at the moment

**Comment by jmoldon** [comment]
Hi Jack,

I have a new self-calibration script, but separate from the main pipeline. It is very flexible, easy to configure the steps and parameters, informative (plots and logs). It can either use tclean or wsclean, include masks, etc. I can put together an example and send it to you.

Regarding MSSC CASA, good, congratulations! I really want to try it. I see you have a repo in your github. If it is up-to-date I will get it and try.

**Comment by jradcliffe5** [comment]
Ok that's great to know and would be good to have a go. I guess one thing we may want to look at putting together is a peeling mechanism too. 

MSSC_CASA is almost ready. I would wait until the end of next week to use it as I'm going to iron out the bugs over the next week as I need to apply it to a VLBA data set soon.
