### ISSUE TITLE
Test data sets

### ISSUE THREAD

**Issue by jmoldon** [e-merlin/eMERLIN_CASA_pipeline#19]
We can write here which types of data sets we want to have as a reference to check the pipeline and to add new features. Jack has added in the wiki links to two data sets observed in mixed mode. We also need smaller data files to quickly check that the pipeline works. I will now link other fits files in the wiki (C, L, K band, just a few visibilities, a single source, etc). They come from the data exporter, so no modification have been added, but still they are < 20 Mb each.

List of possible files to test different but typical situations:

- **running_test**: Very small dataset to check that pipeline works.
- **standard_C**: Continuum C band observation (Target + phase ref + 3C286 + OQ208 + 3C84)
- **no_amp_C**: Continuum C band observation, 3C286 missing for one/several or all antennas (Target + phase ref  + OQ208 + 3C84)
- **no_bp_C**: Continuum C band observation, 3C286 missing for one/several or all antennas (Target + phase ref  + 3C286 + 3C84)
- **mixed_C**: Mixed mode (continuum + spectral lines)
- **partial_C**: Continuum C band with one or more antennas failing (present but garbage data) for part or the whole observation.

And the same for L, and K bands.

Feel free to add more situations or rename them.

**Comment by jradcliffe5** [comment]
Cheers Javier, at the moment the large data sets are wrong so Im removing the links to them. There was a problem with the exporter so Rob is sorting it out atm. Will re-up the links once its been fixed.

**Comment by jradcliffe5** [comment]
Mixed mode data sets are up. Do we need any more data sets now or can we close the issue?
