### ISSUE TITLE
Amplitude scale

### ISSUE THREAD

**Issue by jmoldon** [e-merlin/eMERLIN_CASA_pipeline#33]
- [ ] Amplitude scale
-- Fluxscale
-- dfluxpy
-- setjy
-- Plots

**Comment by jradcliffe5** [comment]
Example of scaling code in this file using the fudging method discussed yesterday.
[20nov2015_cal.py.txt](https://github.com/e-merlin/CASA_eMERLIN_pipeline/files/954188/20nov2015_cal.py.txt)

**Comment by jmoldon** [comment]
Amplitude scale calibration performed from #47.
@daniellefenech will implement the dfluxpy correction.

**Comment by jmoldon** [comment]
Resolved by #100
