### ISSUE TITLE
Minor bugs in fluxscale and bandpass_1_sp steps

### ISSUE THREAD

**Issue by amsrichards** [e-merlin/eMERLIN_CASA_pipeline#52]
The fluxscale step should also mention sety, as this is used to set the newly found flux densities of all calibrators (except the original flux standard) as models in the MS.

Since the fluxscale step does not always use all antennas, the _fluxscaled table is not useful for all antennas and in  bandpass_1_sp the original allcal_ap.G1 should be used.  This is presumably normalised  and will correct the time-variable element of the amps whilst the model with spectral index is used for the flux scale (please check that this does work as I think!).  (The later gaincal steps re-derive a properly scaled amp gain table for all cals).

**Comment by jmoldon** [comment]
Resolved by #100
