### ISSUE TITLE
Logging request: Where is the spectral line data stored and what happens with it

### ISSUE THREAD

**Issue by varenius** [e-merlin/eMERLIN_CASA_pipeline#68]
When running the "fringe-fit"-branch of the pipeline today on a mixed-mode data set, i.e. with both continuum and line spws, I got the following output:
2017-10-25 08:35:29 | INFO | Check for mixed mode
2017-10-25 08:35:29 | INFO | Splitting continuum from spectral line
0,1,2,3
2017-10-25 08:51:59 | INFO | Splitting spectral line
2017-10-25 09:06:23 | INFO | Will continue with continuum, original data is TSARP220_C_20171013.ms.original

It is good that I am informed what is the original data. But I assume nothing has been done to the spectral line data except splitting it to a separate MS - right? If so, it would be nice with a similar logging message, saying eg. "Spectra line data saved to X.MS. No flagging or calibration will be done to these data".

Also, while I'm at it: the current log says "Splitting continuum from spectral line" and then "Splitting spectral line". It seems redundant, but I assume that the first means "extracting continuum SPWs to separate MS" and the next means "extracting line SPWs to separate MS". Perhaps would be good to clarify this.

**Comment by jmoldon** [comment]
Resolved by #100
