### ISSUE TITLE
spwmap in documentation

### ISSUE THREAD

**Issue by amsrichards** [e-merlin/eMERLIN_CASA_pipeline#94]
Hi, I have noticed that the delay tables are derived using combine='spw', but when these are applied sometimes spwmap =[0]*nspw is specified but sometimesspwmap=[].  Also in one place when applying the bandpass table B0, spwmap =[0]*nspw is specified - I guess these are typos. I can mark them up on the printout if you like.  Trivial but confusing ... thanks

**Comment by jmoldon** [comment]
Resolved by #100
