### ISSUE TITLE
Importfitsidi enquiry

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/eMERLIN_CASA_pipeline#98]
Hi Javier, 

I get a whole host of different error messages regarding importfitsidi whenever I use a different version of CASA. On the SPARCS data (observed Mar2018), if i use CASA v4.7.2 I get errors regarding the WEIGHT keyword not found whereas with CASA v.5.1.2 I get no such errors. Do you know if this is an issue or had experience dealing with it?

**Comment by jmoldon** [comment]
Resolved by #100
